export const actionType = {
  ADD_TO_MENU: "ADD_TO_MENU",
  REMOVE_FROM_MENU: "REMOVE_FROM_MENU",
  ADJUST_MENU_QTY: "ADJUST_MENU_QTY",
  ADD_CONTENT: "ADD_CONTENT",
  VIEW_SINGLE_CONTENT: "VIEW_SINGLE_CONTENT"
}